In [2]:
import pandas as pd

In [4]:
brand = pd.read_csv("developer_brand.csv", sep=";")
# brand.head(20)
# developer_brand.csv
# developer_main.csv24 days ago
# district_province_id.csva month ago
# facility_id.csva month ago
# Hackathon data dictionary.xlsx19 days ago
# LICENSE.txt18 days ago
# project_description.csv19 days ago
# project_facility.csva month ago
# project_main.csv24 days ago
# project_unit.csva month ago
# unit_type_id.csva month ago
# userLog_201801_201802_for_participants.csv
brand

,developer_id,brand_id,brand_name_th,brand_name_en
0,128,379,เอสต้า บลิซ,NaN
1,176,1496,บริษัท ชัยยุทธ เรียล เอสเตท จำกัด,NaN
2,226,1819,อะพูล คอนโด แอท บางนา,NaN
3,143,1567,คาซ่า ฟรานซ์ เอแบค-บางนา,NaN
4,250,436,เลอ นีโอ,NaN
5,3588,442,NaN,Chateau In Town
6,9339,1468,บริษัท คีย์ สตาร์ พร็อพเพอร์ตี้,NaN
7,9234,1602,พาร์ค วิลเลจ อ่อนนุช-สุวรรณภูมิ,NaN
8,3647,701,เชียงใหม่พฤกษาโฮม,NaN
9,6248,1346,รื่นฤดี 4 (รังสิต-คลอง 4),NaN
10,15650,1768,เดอะ มาร์ค รัชดา-แอร์พอร์ตลิงค์,NaN
11,6559,846,เอสเคป,NaN
12,1205,465,NaN,Symphony
13,480,1806,คลาส หลังสวน,NaN
14,1145,823,เดอะ รอยัล เรสซิเดนซ์,NaN
15,6168,1894,\tมณีรินทร์ ไพรเวซี่ ศรีราชา,NaN
16,2761,1477,NaN,Zennext
17,2486,641,ทาวน์พลัส เกษตร,NaN
18,20371,998,เบญญาภา คาซ่า,NaN
19,8466,1000,ปรีชา ร่มเกล้า,NaN
20,3047,722,โชติกา โนเวลตี้,NaN
21,17026,770,อารียา ทูบี,NaN
22,16789,1724,ยูทรี คอนโด แอท แยกเกษตร,NaN
23,19226,421,NaN,Ashton
24,16549,1939,นนท์ณิชา บางใหญ่-แก้วอินทร์,NaN
25,4149,817,NaN,The Tuscana
26,19690,272,ริธึ่ม,NaN
27,13231,1565,เดอะ รีเจ้นท์ บาย โบ๊ทเฮ้าส์,NaN
28,18524,271,NaN,The Address
29,19839,1822,สไตล์ลิสท์ เชียงใหม่,NaN
...,...,...,...,...
972,140673,1215,เอริก้า วิลล์,NaN
973,140981,2157,เดอะ แชมเบอรี่,NaN
974,140606,335,T SPACE / ร.8 - มหาวิทยาลัยขอนแก่น,NaN
975,140879,1946,บ้านฉัตรหลวง,NaN
976,140609,1908,รูเนะสุ ทองหล่อ 5,NaN
977,140605,334,NaN,FAIRFORD
978,140872,1932,ซันทารา คอนโดมิเนียม,NaN
979,140610,416,NaN,Amust
980,140874,1937,บ้านไออุ่น,NaN
981,140608,1686,เมลานี แบงคอก,NaN
982,140891,1976,NaN,Ezio
983,140881,1956,เดอะชารีน่า,NaN
984,140890,1975,บ้านบารมี,NaN
985,140880,1952,NaN,Loft Lane Lasalle
986,140899,1992,วีรดา กำแพงเพชร,NaN
987,140883,1965,NaN,Feel Condo Ladprao 33
988,140900,1994,แอมไชน่าทาวน์,NaN
989,140894,1982,NaN,THE SENSE Amphawa
990,140875,1934,บ้านพิมพ์ศิริ สุพรรณ,NaN
991,140607,337,NaN,BEST HOME
992,140902,1998,ไฟคัส เลน,NaN
993,140904,2007,เดอะมอนิ่งไซด์วิลล์,NaN
994,140868,1929,เดอะริชทาวน์ 3,NaN
995,140860,1923,ภูเก็ตโกลเด้นวิลล์,NaN
996,140878,1945,เดอะเฟลกซ์ ทาวน์โฮม,NaN
997,140892,1977,ภัทราโคซี่,NaN
998,140901,1997,อชิลา,NaN
999,140554,638,เดอะ เลเจ้นท์ สาทร,NaN
1000,140905,2005,วนารมย์ วิลเลจ,NaN
1001,141022,2230,บียอนด์ บาย สายลมเย็น,NaN

In [30]:
user_log = pd.read_csv("userLog_201801_201802_for_participants.csv", sep=";")

In [31]:
user_log.tail(20)

,userCode,project_id,requestedDevice,userAgent,pageReferrer,year,month,day,hour
1234559,50194307-ac1a-8fdd-c0d2-920ea71a78b5,6443,Mobile,iPhone,HomeWebsite,2018,2,22,23
1234560,39178c5e-8d92-5a37-634c-b35d9fcc516b,9400,Mobile,iPhone,HomeWebsite,2018,2,22,23
1234561,db06471d-b0c2-2429-bf58-a7e822f837d7,9472,Desktop,Windows,HomeWebsite,2018,2,22,23
1234562,efb828ef-0a75-c6ed-a11d-deca11049e9d,8112,Mobile,iPhone,HomeWebsite,2018,2,22,23
1234563,45df04d6-1d7e-06a8-0a8e-2c5c382689b6,8534,Desktop,Macintosh,Google,2018,2,22,23
1234564,db06471d-b0c2-2429-bf58-a7e822f837d7,9472,Desktop,Windows,HomeWebsite,2018,2,22,23
1234565,7a35eb91-2581-170d-a56b-406405f156c7,7241,Mobile,iPhone,Google,2018,2,22,23
1234566,01ff0d39-da3c-65c2-661a-9ffaac29ddb3,4713,Mobile,iPhone,Google,2018,2,22,23
1234567,b5ae099c-1054-f38c-c178-05d9670980db,5239,Mobile,iPhone,Google,2018,2,22,23
1234568,891ee206-2488-6b6a-d9e1-21987c26f6bf,9447,Mobile,iPhone,HomeWebsite,2018,2,22,23
1234569,ab8efc26-e6f3-2055-4d07-d7e70bf0d7d4,9095,Mobile,Android,HomeWebsite,2018,2,22,23
1234570,7a35eb91-2581-170d-a56b-406405f156c7,7241,Mobile,iPhone,Google,2018,2,22,23
1234571,db06471d-b0c2-2429-bf58-a7e822f837d7,7251,Desktop,Windows,HomeWebsite,2018,2,22,23
1234572,e4f4b92e-c265-08df-6e8f-8ce118ed4c77,6842,Desktop,Windows,Google,2018,2,22,23
1234573,db06471d-b0c2-2429-bf58-a7e822f837d7,7251,Desktop,Windows,HomeWebsite,2018,2,22,23
1234574,7a35eb91-2581-170d-a56b-406405f156c7,7241,Mobile,iPhone,Google,2018,2,22,23
1234575,8e211444-6a32-3f12-e160-edd2e3750df0,5347,Mobile,iPhone,Google,2018,2,22,23
1234576,d4d96ac1-1333-c643-0528-6a84848558e3,2227,Mobile,Android,Google,2018,2,22,23
1234577,efb828ef-0a75-c6ed-a11d-deca11049e9d,8717,Mobile,iPhone,HomeWebsite,2018,2,22,23
1234578,b5ae099c-1054-f38c-c178-05d9670980db,7776,Mobile,iPhone,Google,2018,2,22,23

In [3]:
project_description = pd.read_csv("project_description.csv", sep=";")

In [12]:
project_description['description_th'][0]

'ตั้งอยู่ติดถนนรังสิต-นครนายก  จัดแบ่งผังโครงการเพื่อให้ผู้อยู่อาศัยได้สัมผัสกับธรรมชาติของน้ำด้วยคลอง กว้าง 10 เมตร และทะเลสาบ 2 แห่ง สิ่งอำนวยความสะดวกครบ ใกล้สถานศึกษามหาวิทยาลัย เดินทางสะดวกสบายด้วยถนนวงแหวนตะวันออก'

In [ ]:
proj_unit = pd.read_csv("project_unit.csv", sep=";")